// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP_AHHQK-NmRE9TH4dFcGgZaAFuwi1s6A',
    appId: '1:968434888103:web:7628d91d72e12b95ce9a82',
    messagingSenderId: '968434888103',
    projectId: 'teamchatapp-fe981',
    authDomain: 'teamchatapp-fe981.firebaseapp.com',
    storageBucket: 'teamchatapp-fe981.firebasestorage.app',
    measurementId: 'G-344WGS9BXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCobM138NxkJ3SLzdrbs3mwal0qzPPfZUQ',
    appId: '1:968434888103:android:c6580731661d1310ce9a82',
    messagingSenderId: '968434888103',
    projectId: 'teamchatapp-fe981',
    storageBucket: 'teamchatapp-fe981.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDze6bViHfgLM5rxjn0f4Q74uYJ-DtGMNk',
    appId: '1:968434888103:ios:9167d812c0bf47d2ce9a82',
    messagingSenderId: '968434888103',
    projectId: 'teamchatapp-fe981',
    storageBucket: 'teamchatapp-fe981.firebasestorage.app',
    iosBundleId: 'com.example.teamChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDze6bViHfgLM5rxjn0f4Q74uYJ-DtGMNk',
    appId: '1:968434888103:ios:9167d812c0bf47d2ce9a82',
    messagingSenderId: '968434888103',
    projectId: 'teamchatapp-fe981',
    storageBucket: 'teamchatapp-fe981.firebasestorage.app',
    iosBundleId: 'com.example.teamChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP_AHHQK-NmRE9TH4dFcGgZaAFuwi1s6A',
    appId: '1:968434888103:web:73c03744017cfca5ce9a82',
    messagingSenderId: '968434888103',
    projectId: 'teamchatapp-fe981',
    authDomain: 'teamchatapp-fe981.firebaseapp.com',
    storageBucket: 'teamchatapp-fe981.firebasestorage.app',
    measurementId: 'G-K88HNSEVEL',
  );
}
